### ISSUE TITLE
Weird Api Output

### ISSUE THREAD

**Issue by ampminfo** [mailcow/mailcow-apiblueprint#3]
Using Postman, I tested my mailcow API and got the following output in JSON. I got some Unicode output like &#10003; and &#10005; which are not the same as the documentation when creating 0 or 1... 

{
        "max_new_mailbox_quota": 134217728,
        "def_new_mailbox_quota": 134217728,
        "quota_used_in_domain": "0",
        "bytes_total": 0,
        "msgs_total": 0,
        "mboxes_in_domain": 0,
        "mboxes_left": 10,
        "domain_name": "domain.com",
        "description": "domain.com",
        "max_num_aliases_for_domain": 400,
        "max_num_mboxes_for_domain": 10,
        "def_quota_for_mbox": 134217728,
        "max_quota_for_mbox": 134217728,
        "max_quota_for_domain": 10737418240,
        "relayhost": "0",
        "backupmx": "&#10003;",
        "gal": "&#10005;",
        "backupmx_int": 1,
        "gal_int": 0,
        "rl": false,
        "active": "&#10003;",
        "active_int": 1,
        "relay_all_recipients": "&#10003;",
        "relay_unknown_only": "&#10005;",
        "relay_all_recipients_int": 1,
        "relay_unknown_only_int": 0,
        "aliases_in_domain": 0,
        "aliases_left": 400,
        "domain_admins": "-"
    },

**Comment by ampminfo** [comment]
&#10003 &#10005   I removed the semi-colon to allow my real output

**Comment by andryyy** [comment]
Hi,

Update your cow, should align with the API docs then. :)
